# Generated by Django 4.1.7 on 2023-03-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='election_survey_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('party_name', models.CharField(choices=[('AAA', 'AAA'), ('AAB', 'AAB'), ('AAC', 'AAC'), ('AAD', 'AAD')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
